const express = require("express");
const router = express.Router();
const { Spot, Review, SpotImage, User, ReviewImage, Booking, Sequelize } = require("../../db/models");
const { where } = require("sequelize");
const { currentSpot } = require('./spots') ;

router.get('/current', async (req, res, next) => {
    const { user } = req

    const bookings = await Booking.findAll({
        where: {
            userId: user.id
        }
    })

    return res.json(bookings)
})

router.put('/:bookingId', async (req, res, next) => {
    const id = req.params.bookingId
    const booking = await Booking.findByPk(id)
    const body = req.body
    
try {
    await booking.update(body)
    return res.json(booking)
    
} catch (error) {
    if (!booking) return res.json({"message": "Booking couldn't be found"})
    else if (booking.startDate < Sequelize.literal("CURRENT_TIMESTAMP")) res.json({"message": "Past bookings can't be modified"})
    else if (body.startDate === booking.startDate && body.endDate === booking.endDate) return res.json({
        "message": "Sorry, this spot is already booked for the specified dates",
        "errors": {
          "startDate": "Start date conflicts with an existing booking",
          "endDate": "End date conflicts with an existing booking"
        }
      })
    else return res.json({
        "message": "Bad Request", // (or "Validation error" if generated by Sequelize),
  "errors": {
    "startDate": "startDate cannot be in the past",
    "endDate": "endDate cannot be on or before startDate"
  }
    })
}
})

router.delete('/:bookingId', async (req, res, next) => {
    
    try {
        let id = req.params.bookingId
        let booking = await Booking.findByPk(id)
        if(!booking) throw new Error()
        await booking.destroy()
        return res.json({"message": "Successfully deleted"})
        
    } catch (error) {
        let booking = await Booking.findByPk(id)
        if (!booking) return res.json({"message": "Booking couldn't be found"})
        else return res.json({"message": "Bookings that have been started can't be deleted"})
    }
})


module.exports = router